### ISSUE TITLE
issue with offline-plugin

### ISSUE THREAD

**Issue by tuananh** [lukeed/pwa#21]
I got this issue with offline plugin. The link in the error recommends that i add this `require('offline-plugin/runtime').install();` but i'm not sure where to add it .

```
OfflinePlugin: Plugin's runtime wasn't added to one of your bundle entries. See this https://goo.gl/YwewYp for details.
````

**Comment by lukeed** [comment]
Verified this locally, and there'll now be a `@pwa/plugin-offline` in the next release. Similarly, attaching Service Workers will be included in `init`'s scaffolding. 👍
