### ISSUE TITLE
Getting 404

### ISSUE THREAD

**Issue by subpx** [lukeed/pwa#23]
Followed setup instructions. Open localhost:8080 in browser and get 404.

**Comment by subpx** [comment]
Svelte / Navaid / SASS
Works when I change port. 
You can probably close this. I would say its something messing with 8080 locally for me.

**Comment by lukeed** [comment]
Ah yeah, sorry. The [`svelte-router`](https://github.com/lukeed/pwa/blob/master/packages/cli/templates/svelte-router/index.js) template is completely empty right now. There's no app to produce/generate, so WDS probably freaks out and gives a 404.

I just finished designing the router template(s) – by end of the day I'll have them all uploaded & I'll publish `0.2.0` 👍 

Lemme know if you run into other issues!
