### ISSUE TITLE
add install instructions to readme

### ISSUE THREAD

**Issue by sibelius** [lukeed/pwa#24]
```
npm i -g @pwa/cli
```

or

```
yarn global add @pwa/cli
```

**Comment by WYoYao** [comment]
run pwa init.
 Cannot find module 'tiny-glob/sync'

**Comment by JacobMGEvans** [comment]
@WYoYao That seems like a different issue. Maybe open another issue and add more of information if you can. I guess if that is all that the terminal is showing and no stack trace then that's what you got. 

Though this is an installation addition to the readme issue. Not a usage of the CLI issue. :smile:

**Comment by lukeed** [comment]
Closed via 078c4a70fe6784cbd97b8a63f477f4688d881e2c

@WYoYao What's your Node version? Did you install with `pnpm`? 

I know `pnpm` doesn't resolve internal module paths consistently/correctly.
