### ISSUE TITLE
Watch: `--https` flag overrides custom config

### ISSUE THREAD

**Issue by tuananh** [lukeed/pwa#26]
i have this line in `pwa.config.js`

    config.devServer.https = true

however, when i browse to `https://localhost:8080` it shows `ERR_SSL_PROTOCOL_ERROR`

Do you have any idea why it happens? should i bring this to webpack devserver repo instead?

**Comment by lukeed** [comment]
Hey, this would be a WDS error, if anything. Although it sounds like your system is rejecting the certificate they're adding for you.

I'm sure they have docs/FAQ for that somewhere! You could also provide custom key and cert values, even if you just generate them quickly with openssl.

Closing as this isn't PWA related, but lemme know if you find the answer!
