### ISSUE TITLE
TypeScript Plugin

### ISSUE THREAD

**Issue by lukeed** [lukeed/pwa#5]
- [x] Should include `.tsx?` as module extension
- [x] Should swap out `babel-loader` for itself
- [ ] Should expect `typescript` config key?
      _The standard TS config/rc file already works._

---

I think there may need to be separate `@pwa/plugin-{preset}-typescript` plugins for (React/Vue/etc)-specific handling of TypeScript. Same goes with test suite(s).

**Comment by olso** [comment]
How is this looking ❤️

**Comment by lukeed** [comment]
@olso Great, actually! I was tempted to force it into `0.3.0` but making it a key feature of the next minor release.

I want to bundle in TS, TSLint, and ideally an Angular preset (#8) into  `0.4.0`. That'd make for a good milestone, I think 😄

**Comment by tzvipm** [comment]
Hey @lukeed, I'd love to get involved with this project. Do you have a contributing guide / slack channel / something?
