### ISSUE TITLE
Export to relative paths?

### ISSUE THREAD

**Issue by tiptronic** [lukeed/pwa#53]
Right now `pwa export` exports to an absolute path (root). Which config do I need to generate relative paths?

**Comment by lukeed** [comment]
You should be able to just do `--dest <target>` on either your `build` or `export` commands.

```sh
$ pwa export --dest foobar

# => foobar/index.html
# => foobar/about/index.html
# => etc
```

**Comment by tiptronic** [comment]
Did you try?
I tried 
`$ pwa export --dest .`
and it deleted the whole project 😱

**Comment by lukeed** [comment]
Ah, I misunderstood you – sorry. The `--dest` flag changes _where_ the build files are placed. It also clears the existing/previous files to ensure it's a clean build. I hope you were able to recover your files!

As for relative pathing, that's controlled by webpack's `output.publicPath` config. It is `/` by default (in both PWA and webpack).

To change it, you do this:

```js
// pwa.config.js
exports.webpack = function (config) {
  config.output.publicPath = './'; // or whatever you want
}
```

That will update all the **webpack-controlled** asset pathing.

In the snippet you pasted above, that means that (only) `/bundle.7c264.css` will become `./bundle.7c264.css`.

To change the `/assets/favicon.png` and `/assets/manifest.json` you have to manually change those in your `src/index.html` – which PWA scaffolded for you during `init` phase.

---

I've tested the above config & made the changes to `src/index.html`'s meta tags. All works as you've requested. 

You do not need the `--dest` flag – sorry for misunderstanding the question initially.

Hope that helps!

**Comment by lukeed** [comment]
I think it was mostly my fault, not to worry!

I'm trying to set aside some time to do another sprint of PWA changes. It hasn't been super high on my list lately, simply because it works reliably for my needs now. ...But I definitely need to make sure the documentation is up to par & that the tools that _others_ use are supported.
