### ISSUE TITLE
How do I deloy on a heroku server?

### ISSUE THREAD

**Issue by alefemafra** [lukeed/pwa#57]

**Comment by lukeed** [comment]
Same way you'd deploy any other static site. I don't use Heroku so I couldn't tell you how, but everything PWA deals with is frontend code. No server configs here. Your output is HTML, JS, and CSS only, so you only need to deal with static deployment.

Hope that helps!

**Comment by alefemafra** [comment]
Helle,

I used a build-react-app buildpack, so I disabled the build command, so in case I do the local build, and it works correctly, but still thanks for the help.
