### ISSUE TITLE
ServiceWorker Plugins

### ISSUE THREAD

**Issue by lukeed** [lukeed/pwa#6]
- [x] Offline Plugin
- [x] SW Precache
- [x] SW Workbox

---

ServiceWorker already _works_ thru manual `webpack` config mgmt...

```js
// pwa.config.js
const SWPrecache = require('sw-precache-webpack-plugin');

exports.webpack = function (config, env) {
  if (env.production) {
    config.plugins.push(
      new SWPrecache({ ... })
    );
  }
}
```

... but it'd be nice to have this done automatically, just because the plugin(s) exist.

**Comment by tuananh** [comment]
i already add the above snippet to my `pwa.config.js` but lighthouse still complains that `Does not register a service worker`.

**Comment by lukeed** [comment]
Hey, so `watch` is not production mode. You should always run `pwa build` (or export) and then `yarn start` before auditing. The `env.production` is not true in watch mode.

In addition to the config snippet above, you must also add this to your `src/index.js`

```js
if (process.env.NODE_ENV === 'production') {
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('/sw.js');
  }
}
```

That actually registers / attaches the SW you produce with the plugin.
