### ISSUE TITLE
Help, how to remove .svelte file from browser source

### ISSUE THREAD

**Issue by odick** [lukeed/pwa#67]
![Screenshot from 2019-11-13 20 13 19](https://user-images.githubusercontent.com/1612324/68764059-eeb3c600-0654-11ea-8bf3-ccb2cb1f8f41.png)
Webpack devtools is false on production but still see the svelte file from browser source
Any help on this @lukeed @olso

**Comment by lukeed** [comment]
Need source and/or reproduction

**Comment by odick** [comment]
I test with the default sample cli (pwa init) and the result is the same
Test with vue preset, no vue files on the source but same problem with the svelte preset
Some screenshot:
INIT PWA
![Screenshot from 2019-11-14 11 05 07](https://user-images.githubusercontent.com/1612324/68824193-f5801e80-06d0-11ea-84ec-48ba6f151b7f.png)
RUN START
![Screenshot from 2019-11-14 11 17 35](https://user-images.githubusercontent.com/1612324/68824216-06309480-06d1-11ea-877b-abfbf5288d19.png)
NOW add disable devtools
![Screenshot from 2019-11-14 11 28 15](https://user-images.githubusercontent.com/1612324/68824483-f49bbc80-06d1-11ea-8db8-bc2c32d0288e.png)
Webpack source map gone, but the svelte code still in source
Please help, thank you

**Comment by odick** [comment]
@lukeed I found the solution, just set this to false https://github.com/lukeed/pwa/blob/b3b928a0880f58d9cae6a45c6270dbbc67dfb2a0/packages/preset-svelte/index.js#L43
And all the svelte file from removed from the browser source
But as a result, svelte will not generate css in the build

Any clue on how to set emitCss to false in pwa.config.js?
Thank you
