### ISSUE TITLE
Duplicated App in svelte production

### ISSUE THREAD

**Issue by pupubird** [lukeed/pwa#68]
Hi! I am trying out this exciting project for Svelte!
The step to recreate the issue:

Environment:
Chrome, svelte with route and offline-plugin

1. go to any route
2. hits the refresh button
3. And I will see the duplicated app like this

It works fine if I directly land on the page, 
![image](https://user-images.githubusercontent.com/35325976/77098700-bc283880-6a4d-11ea-844f-fb21f51a6958.png)

but when I hit the refresh button, it will be duplicated

![image](https://user-images.githubusercontent.com/35325976/77098049-b67e2300-6a4c-11ea-97e1-c2c74005d7c8.png)

Some information that I think might help:

1. If I run `npm run build` again, the amount of duplicated = the amount of time I run the command
2. Only home page won't have this issue, other pages will have this issue

I tried:

1. delete the build folder and run again
2. clear all data in chrome

May I know how should I resolve this issue? Very much thanks

**Comment by lukeed** [comment]
Hey, thanks for raising an issue!

Looks like the svelte template is missing this within the `src/index.js` file:

```js
window.app = new App({
	// ...
	hydrate: true // <~ add this
});
```

Verified it on my end. Please let me know if it works for you

**Comment by pupubird** [comment]
The duplicated app issue is gone! Thanksss

But in the meantime... this issue came up

![image](https://user-images.githubusercontent.com/35325976/77143606-aa32ae00-6abe-11ea-8722-64cf2608d3a4.png)

then when I hit refresh again:

![image](https://user-images.githubusercontent.com/35325976/77143631-ba4a8d80-6abe-11ea-9e94-54f0248bb2c8.png)

This came up!
