### ISSUE TITLE
Create sub-folder in pages folder [Svelte]

### ISSUE THREAD

**Issue by pupubird** [lukeed/pwa#69]
Hi!
So I had been trying to make a sub-folder in the pages folder like this:
![1](https://user-images.githubusercontent.com/35325976/77619254-ccbb4000-6f72-11ea-99e7-0241f19db262.PNG)

I also remove the --export flag in config.json to let it scrape programmatically.
![2](https://user-images.githubusercontent.com/35325976/77619291-e0ff3d00-6f72-11ea-86e8-a211b6ed5b09.PNG)

But the outcome be like this:
![3](https://user-images.githubusercontent.com/35325976/77619327-f6746700-6f72-11ea-9a96-8e753de5799c.PNG)
How should I make it knows that `Blog.svelte` be the home of the path?

**Comment by lukeed** [comment]
Hey,

It doesn't treat lowercase directory names any differently, that's why it's writing both "blog" segments. 

Try naming it "pages/blog/Index.svelte"

**Comment by pupubird** [comment]
Ah! It works as expected now, thanks!
