### ISSUE TITLE
@pwa/plugin-typescript is not published

### ISSUE THREAD

**Issue by tatchi** [lukeed/pwa#70]
Got an error when bootstrapping a project with typescript. Looks like the package has not yet been published to npm yet

**Comment by lukeed** [comment]
Oh man, that's...not good. And embarrassing.

Going to have to see what's up with my lerna script 🙈 

Published manually & it's now available. Thanks!

**Comment by tatchi** [comment]
> Oh man, that's...not good. And embarrassing.
> 
> Going to have to see what's up with my lerna script 🙈
> 
> Published manually & it's now available. Thanks!

No worries. Thanks for sharing all these amazing libs! Can't imagine the number of people you have helped so far  🤗
